### ISSUE TITLE
Create Nuget Package

### ISSUE THREAD

**Issue by furesoft** [dubiousconst282/DistIL#10]
add Nuget package to easily add it to custom projects

**Comment by dubiousconst282** [comment]
Hi, thanks for the interest.

DistIL is not stable yet for production usage (or really any actual serious use), though I believe it is getting close.

While it does work when applied to relatively simple apps, some break in either subtle ways or entirely - for example, ILSpy.Decompiler, fails to decompile many cases, while ImageSharp crashes when trying to decode a Jpeg, and a lot of its tests are failing. I believe these issues are caused by a few bugs around integer coercion/truncation on local variables.

Once it does gets there, I think it would make sense to distribute it as a Nuget package which integrates with MSBuild like other projects such as Fody, but I'm not very familiar with this stuff yet. The actual library would be made available as well.

**Comment by furesoft** [comment]
I would really appreciate it and would like to use it on my future compiler projects

**Comment by dubiousconst282** [comment]
I've just published an early pre-release package: https://www.nuget.org/packages/DistIL.Core

It's now able to process ImageSharp and ICSharpCode.Decompiler libraries, but I still stress that some things are still in very rough shape. There's no documentation yet, but the [CLI Program.cs](https://github.com/dubiousconst282/DistIL/blob/main/src/DistIL.Cli/Program.cs) might be a good start, if you're interested.
