### ISSUE TITLE
Problem finding entrypoint

### ISSUE THREAD

**Issue by furesoft** [dubiousconst282/DistIL#37]
Hi,

I created a test application here: https://github.com/furesoft/compiler-test
but the compiled.dll cannot be run by the .net runtime with this error: Unhandled exception. System.MethodAccessException: Entry point must have a return type of void, integer, or unsigned integer.

Am I doing something wrong?

Thanks

**Comment by dubiousconst282** [comment]
The problem here seems to be the use of `moduleResolver.SysTypes.Void` instead of `PrimType.Void` in the method signature, it's a quirk of DistIL's type system as PrimTypes are directly equivalent to the primitive types in the CIL spec, whereas SysTypes are just references to the definitions in CoreLib.

Replacing to the following works for me:

```
        var main = program.CreateMethod("Main", new TypeSig(PrimType.Void), [], MethodAttributes.Static | MethodAttributes.Public | MethodAttributes.HideBySig);
```

This seems to be a special case not handled by the runtime though, I'm not sure if the module emitter should be normalizing these types.

**Comment by furesoft** [comment]
Thanks a lot

**Comment by furesoft** [comment]
so when to use PrimType and when use SysTypes?

**Comment by dubiousconst282** [comment]
`PrimType` should be preferred, SysTypes is only useful for a few specific cases like referencing Int32.ToString() and other members.

The equality operators treat both as equal btw, so PrimType.Int32 == SysTypes.Int32, even though they are of different class types. This might be another source of bugs and it's something that might change in the future.
